#
#  Copyright Christopher Di Bella
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
task:
  env:
    matrix:
      COMPILER_VERSION: 8
    matrix:
      BUILD_TYPE: Debug
      BUILD_TYPE: Release
  container:
    dockerfile: config/ci/Dockerfile
    cpu: 8
    memory: 16G
  configure_script:
    - mkdir -p build
    - cd build
    - export CC=`which gcc-${COMPILER_VERSION}`
    - export CXX=`which g++-${COMPILER_VERSION}`
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"
  build_script:
    - cd build
    - ninja -v
  test_script:
    - cd build
    - ctest -j8 --output-on-failure
