TEMPLATE = app

CONFIG -= app_bundle qt
CONFIG += console c++11

DEFINES += RANGES_SUPPRESS_IOTA_WARNING

win32-g++ {
QMAKE_CXXFLAGS += -pedantic -march=native -ffast-math -mfpmath=both
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE += -O3 -DNDEBUG
}

SOURCES += main.cpp

INCLUDEPATH += ../misc ../../boost ../../range-v3/include

HEADERS += \
    ../misc/mutex.hpp \
    ../misc/thread.hpp \
    ../misc/instrumented.hpp \
    ../misc/print_sequence.hpp \
    ../misc/make_unique.hpp \
    ../misc/algorithm.hpp \
    ../misc/integer_sequence.hpp \
    ../misc/make_array.hpp \
    ../misc/static_vector.hpp \
    ../misc/type_traits.hpp \
    ../misc/iterator.hpp \
    ../misc/memory.hpp \
    ../misc/swap.hpp \
    ../misc/utility.hpp \
    ../misc/sync.hpp \
    ../misc/string_view.hpp \
    ../misc/array.hpp \
    ../misc/condition_variable.hpp \
    ../misc/optional.hpp \
    ../misc/random.hpp \
    ../misc/runtime_array.hpp \
    ../misc/seminumeric.hpp \
    ../misc/tuple.hpp \
    ../misc/odr_const.hpp \
    ../misc/functional.hpp \
    ../misc/iter_swap.hpp \
    ../../range-v3/include/range/v3/action/action.hpp \
    ../../range-v3/include/range/v3/action/concepts.hpp \
    ../../range-v3/include/range/v3/action/drop.hpp \
    ../../range-v3/include/range/v3/action/drop_while.hpp \
    ../../range-v3/include/range/v3/action/erase.hpp \
    ../../range-v3/include/range/v3/action/insert.hpp \
    ../../range-v3/include/range/v3/action/join.hpp \
    ../../range-v3/include/range/v3/action/push_back.hpp \
    ../../range-v3/include/range/v3/action/push_front.hpp \
    ../../range-v3/include/range/v3/action/remove_if.hpp \
    ../../range-v3/include/range/v3/action/slice.hpp \
    ../../range-v3/include/range/v3/action/sort.hpp \
    ../../range-v3/include/range/v3/action/split.hpp \
    ../../range-v3/include/range/v3/action/stable_sort.hpp \
    ../../range-v3/include/range/v3/action/stride.hpp \
    ../../range-v3/include/range/v3/action/take.hpp \
    ../../range-v3/include/range/v3/action/take_while.hpp \
    ../../range-v3/include/range/v3/action/transform.hpp \
    ../../range-v3/include/range/v3/action/unique.hpp \
    ../../range-v3/include/range/v3/action.hpp \
    ../../range-v3/include/range/v3/algorithm.hpp \
    ../../range-v3/include/range/v3/all.hpp \
    ../../range-v3/include/range/v3/at.hpp \
    ../../range-v3/include/range/v3/back.hpp \
    ../../range-v3/include/range/v3/begin_end.hpp \
    ../../range-v3/include/range/v3/core.hpp \
    ../../range-v3/include/range/v3/distance.hpp \
    ../../range-v3/include/range/v3/empty.hpp \
    ../../range-v3/include/range/v3/front.hpp \
    ../../range-v3/include/range/v3/getlines.hpp \
    ../../range-v3/include/range/v3/istream_range.hpp \
    ../../range-v3/include/range/v3/numeric.hpp \
    ../../range-v3/include/range/v3/range.hpp \
    ../../range-v3/include/range/v3/range_access.hpp \
    ../../range-v3/include/range/v3/range_adaptor.hpp \
    ../../range-v3/include/range/v3/range_concepts.hpp \
    ../../range-v3/include/range/v3/range_facade.hpp \
    ../../range-v3/include/range/v3/range_for.hpp \
    ../../range-v3/include/range/v3/range_fwd.hpp \
    ../../range-v3/include/range/v3/range_interface.hpp \
    ../../range-v3/include/range/v3/range_traits.hpp \
    ../../range-v3/include/range/v3/size.hpp \
    ../../range-v3/include/range/v3/to_container.hpp \
    ../../range-v3/include/range/v3/view.hpp \
    ../../range-v3/include/range/v3/algorithm/adjacent_find.hpp \
    ../../range-v3/include/range/v3/algorithm/all_of.hpp \
    ../../range-v3/include/range/v3/algorithm/any_of.hpp \
    ../../range-v3/include/range/v3/algorithm/binary_search.hpp \
    ../../range-v3/include/range/v3/algorithm/copy.hpp \
    ../../range-v3/include/range/v3/algorithm/copy_backward.hpp \
    ../../range-v3/include/range/v3/algorithm/copy_if.hpp \
    ../../range-v3/include/range/v3/algorithm/copy_n.hpp \
    ../../range-v3/include/range/v3/algorithm/count.hpp \
    ../../range-v3/include/range/v3/algorithm/count_if.hpp \
    ../../range-v3/include/range/v3/algorithm/equal.hpp \
    ../../range-v3/include/range/v3/algorithm/equal_range.hpp \
    ../../range-v3/include/range/v3/algorithm/fill.hpp \
    ../../range-v3/include/range/v3/algorithm/fill_n.hpp \
    ../../range-v3/include/range/v3/algorithm/find.hpp \
    ../../range-v3/include/range/v3/algorithm/find_end.hpp \
    ../../range-v3/include/range/v3/algorithm/find_first_of.hpp \
    ../../range-v3/include/range/v3/algorithm/find_if.hpp \
    ../../range-v3/include/range/v3/algorithm/find_if_not.hpp \
    ../../range-v3/include/range/v3/algorithm/for_each.hpp \
    ../../range-v3/include/range/v3/algorithm/generate.hpp \
    ../../range-v3/include/range/v3/algorithm/generate_n.hpp \
    ../../range-v3/include/range/v3/algorithm/heap_algorithm.hpp \
    ../../range-v3/include/range/v3/algorithm/inplace_merge.hpp \
    ../../range-v3/include/range/v3/algorithm/is_partitioned.hpp \
    ../../range-v3/include/range/v3/algorithm/is_sorted.hpp \
    ../../range-v3/include/range/v3/algorithm/is_sorted_until.hpp \
    ../../range-v3/include/range/v3/algorithm/lexicographical_compare.hpp \
    ../../range-v3/include/range/v3/algorithm/lower_bound.hpp \
    ../../range-v3/include/range/v3/algorithm/max_element.hpp \
    ../../range-v3/include/range/v3/algorithm/merge.hpp \
    ../../range-v3/include/range/v3/algorithm/merge_move.hpp \
    ../../range-v3/include/range/v3/algorithm/min_element.hpp \
    ../../range-v3/include/range/v3/algorithm/minmax_element.hpp \
    ../../range-v3/include/range/v3/algorithm/mismatch.hpp \
    ../../range-v3/include/range/v3/algorithm/move.hpp \
    ../../range-v3/include/range/v3/algorithm/move_backward.hpp \
    ../../range-v3/include/range/v3/algorithm/none_of.hpp \
    ../../range-v3/include/range/v3/algorithm/nth_element.hpp \
    ../../range-v3/include/range/v3/algorithm/partial_sort.hpp \
    ../../range-v3/include/range/v3/algorithm/partial_sort_copy.hpp \
    ../../range-v3/include/range/v3/algorithm/partition.hpp \
    ../../range-v3/include/range/v3/algorithm/partition_copy.hpp \
    ../../range-v3/include/range/v3/algorithm/partition_move.hpp \
    ../../range-v3/include/range/v3/algorithm/partition_point.hpp \
    ../../range-v3/include/range/v3/algorithm/permutation.hpp \
    ../../range-v3/include/range/v3/algorithm/random_shuffle.hpp \
    ../../range-v3/include/range/v3/algorithm/remove.hpp \
    ../../range-v3/include/range/v3/algorithm/remove_copy.hpp \
    ../../range-v3/include/range/v3/algorithm/remove_copy_if.hpp \
    ../../range-v3/include/range/v3/algorithm/remove_if.hpp \
    ../../range-v3/include/range/v3/algorithm/replace.hpp \
    ../../range-v3/include/range/v3/algorithm/replace_copy.hpp \
    ../../range-v3/include/range/v3/algorithm/replace_copy_if.hpp \
    ../../range-v3/include/range/v3/algorithm/replace_if.hpp \
    ../../range-v3/include/range/v3/algorithm/reverse.hpp \
    ../../range-v3/include/range/v3/algorithm/reverse_copy.hpp \
    ../../range-v3/include/range/v3/algorithm/rotate.hpp \
    ../../range-v3/include/range/v3/algorithm/rotate_copy.hpp \
    ../../range-v3/include/range/v3/algorithm/search.hpp \
    ../../range-v3/include/range/v3/algorithm/search_n.hpp \
    ../../range-v3/include/range/v3/algorithm/set_algorithm.hpp \
    ../../range-v3/include/range/v3/algorithm/shuffle.hpp \
    ../../range-v3/include/range/v3/algorithm/sort.hpp \
    ../../range-v3/include/range/v3/algorithm/stable_partition.hpp \
    ../../range-v3/include/range/v3/algorithm/stable_sort.hpp \
    ../../range-v3/include/range/v3/algorithm/swap_ranges.hpp \
    ../../range-v3/include/range/v3/algorithm/transform.hpp \
    ../../range-v3/include/range/v3/algorithm/unique.hpp \
    ../../range-v3/include/range/v3/algorithm/unique_copy.hpp \
    ../../range-v3/include/range/v3/algorithm/upper_bound.hpp \
    ../../range-v3/include/range/v3/algorithm/aux_/equal_range_n.hpp \
    ../../range-v3/include/range/v3/algorithm/aux_/lower_bound_n.hpp \
    ../../range-v3/include/range/v3/algorithm/aux_/merge_n.hpp \
    ../../range-v3/include/range/v3/algorithm/aux_/merge_n_with_buffer.hpp \
    ../../range-v3/include/range/v3/algorithm/aux_/sort_n_with_buffer.hpp \
    ../../range-v3/include/range/v3/algorithm/aux_/upper_bound_n.hpp \
    ../../range-v3/include/range/v3/detail/config.hpp \
    ../../range-v3/include/range/v3/detail/disable_warnings.hpp \
    ../../range-v3/include/range/v3/detail/re_enable_warnings.hpp \
    ../../range-v3/include/range/v3/numeric/accumulate.hpp \
    ../../range-v3/include/range/v3/numeric/adjacent_difference.hpp \
    ../../range-v3/include/range/v3/numeric/inner_product.hpp \
    ../../range-v3/include/range/v3/numeric/iota.hpp \
    ../../range-v3/include/range/v3/numeric/partial_sum.hpp \
    ../../range-v3/include/range/v3/utility/associated_types.hpp \
    ../../range-v3/include/range/v3/utility/basic_iterator.hpp \
    ../../range-v3/include/range/v3/utility/box.hpp \
    ../../range-v3/include/range/v3/utility/common_iterator.hpp \
    ../../range-v3/include/range/v3/utility/common_tuple.hpp \
    ../../range-v3/include/range/v3/utility/common_type.hpp \
    ../../range-v3/include/range/v3/utility/compressed_pair.hpp \
    ../../range-v3/include/range/v3/utility/compressed_tuple.hpp \
    ../../range-v3/include/range/v3/utility/concepts.hpp \
    ../../range-v3/include/range/v3/utility/copy.hpp \
    ../../range-v3/include/range/v3/utility/counted_iterator.hpp \
    ../../range-v3/include/range/v3/utility/dangling.hpp \
    ../../range-v3/include/range/v3/utility/functional.hpp \
    ../../range-v3/include/range/v3/utility/get.hpp \
    ../../range-v3/include/range/v3/utility/infinity.hpp \
    ../../range-v3/include/range/v3/utility/integer_sequence.hpp \
    ../../range-v3/include/range/v3/utility/is_infinity.hpp \
    ../../range-v3/include/range/v3/utility/iterator.hpp \
    ../../range-v3/include/range/v3/utility/iterator_concepts.hpp \
    ../../range-v3/include/range/v3/utility/iterator_traits.hpp \
    ../../range-v3/include/range/v3/utility/memory.hpp \
    ../../range-v3/include/range/v3/utility/meta.hpp \
    ../../range-v3/include/range/v3/utility/move.hpp \
    ../../range-v3/include/range/v3/utility/nullptr_v.hpp \
    ../../range-v3/include/range/v3/utility/optional.hpp \
    ../../range-v3/include/range/v3/utility/safe_int.hpp \
    ../../range-v3/include/range/v3/utility/semiregular.hpp \
    ../../range-v3/include/range/v3/utility/static_const.hpp \
    ../../range-v3/include/range/v3/utility/swap.hpp \
    ../../range-v3/include/range/v3/utility/tuple_algorithm.hpp \
    ../../range-v3/include/range/v3/utility/unreachable.hpp \
    ../../range-v3/include/range/v3/utility/variant.hpp \
    ../../range-v3/include/range/v3/view/adjacent_remove_if.hpp \
    ../../range-v3/include/range/v3/view/all.hpp \
    ../../range-v3/include/range/v3/view/any_range.hpp \
    ../../range-v3/include/range/v3/view/bounded.hpp \
    ../../range-v3/include/range/v3/view/c_str.hpp \
    ../../range-v3/include/range/v3/view/chunk.hpp \
    ../../range-v3/include/range/v3/view/concat.hpp \
    ../../range-v3/include/range/v3/view/const.hpp \
    ../../range-v3/include/range/v3/view/counted.hpp \
    ../../range-v3/include/range/v3/view/delimit.hpp \
    ../../range-v3/include/range/v3/view/drop.hpp \
    ../../range-v3/include/range/v3/view/drop_while.hpp \
    ../../range-v3/include/range/v3/view/empty.hpp \
    ../../range-v3/include/range/v3/view/filter.hpp \
    ../../range-v3/include/range/v3/view/for_each.hpp \
    ../../range-v3/include/range/v3/view/generate.hpp \
    ../../range-v3/include/range/v3/view/generate_n.hpp \
    ../../range-v3/include/range/v3/view/group_by.hpp \
    ../../range-v3/include/range/v3/view/indirect.hpp \
    ../../range-v3/include/range/v3/view/intersperse.hpp \
    ../../range-v3/include/range/v3/view/iota.hpp \
    ../../range-v3/include/range/v3/view/join.hpp \
    ../../range-v3/include/range/v3/view/map.hpp \
    ../../range-v3/include/range/v3/view/move.hpp \
    ../../range-v3/include/range/v3/view/partial_sum.hpp \
    ../../range-v3/include/range/v3/view/remove_if.hpp \
    ../../range-v3/include/range/v3/view/repeat.hpp \
    ../../range-v3/include/range/v3/view/repeat_n.hpp \
    ../../range-v3/include/range/v3/view/replace.hpp \
    ../../range-v3/include/range/v3/view/replace_if.hpp \
    ../../range-v3/include/range/v3/view/reverse.hpp \
    ../../range-v3/include/range/v3/view/single.hpp \
    ../../range-v3/include/range/v3/view/slice.hpp \
    ../../range-v3/include/range/v3/view/split.hpp \
    ../../range-v3/include/range/v3/view/stride.hpp \
    ../../range-v3/include/range/v3/view/tail.hpp \
    ../../range-v3/include/range/v3/view/take.hpp \
    ../../range-v3/include/range/v3/view/take_exactly.hpp \
    ../../range-v3/include/range/v3/view/take_while.hpp \
    ../../range-v3/include/range/v3/view/tokenize.hpp \
    ../../range-v3/include/range/v3/view/transform.hpp \
    ../../range-v3/include/range/v3/view/unbounded.hpp \
    ../../range-v3/include/range/v3/view/unique.hpp \
    ../../range-v3/include/range/v3/view/view.hpp \
    ../../range-v3/include/range/v3/view/zip.hpp \
    ../../range-v3/include/range/v3/view/zip_with.hpp
