# cmcstl2 - A concept-enabled C++ standard library
# Project home: https://github.com/caseycarter/cmcstl2
#
#  Copyright Casey Carter
#
# SPDX-License-Identifier: (BSL-1.0 OR Apache-2.0 WITH LLVM-exception)
#
FROM ubuntu:disco

# Install packages
RUN apt update
RUN apt upgrade -y
RUN apt update
RUN apt install -y git cmake ninja-build g++-8 g++-9
